### ISSUE TITLE
Determine Pixel Density (DPI)

### ISSUE THREAD

**Issue by Clapfire** [Clapfire/oip_image_processing_assignment_1#2]
Along the bottom of the image, there is a scale. This scale should be used to determine the size of the image.

![image](https://user-images.githubusercontent.com/36258114/67856634-47437900-fb15-11e9-84ce-c95c8d26d0f8.png)

The length of the line in pixels should be found. Then this value can be used to calculate the the DPI.

- [x] Find line in image
- [x] Determine line length in pixels
- [x] Calculate the DPI

**Comment by tamaragaede** [comment]
I opted instead for calculating the pixel size as this makes further computation much simpler.

**Comment by Clapfire** [comment]
Closed by #19
