### ISSUE TITLE
Tilt image to correct slant

### ISSUE THREAD

**Issue by Clapfire** [Clapfire/oip_image_processing_assignment_1#4]
The image is slightly askew. This offset should be corrected by rotating the image into the correct orientation.

![image](https://user-images.githubusercontent.com/36258114/67857093-36473780-fb16-11e9-8e6c-5ca7b2cde2a5.png)

As seen above, the image is slightly tilted counterclockwise.
This step will be done after removing the legend.

**Comment by nicklasfrahm** [comment]
Implemented by #23.
