### ISSUE TITLE
Separate Clusters into Single Beads

### ISSUE THREAD

**Issue by Clapfire** [Clapfire/oip_image_processing_assignment_1#6]
Each cluster should be processed so that it consists of evenly sized beads.
This can possibly be achieved using watershed, or a similar process.

Good:
![image](https://user-images.githubusercontent.com/36258114/67857409-fe8cbf80-fb16-11e9-97c2-8db159fc26c1.png)

Bad:
![image](https://user-images.githubusercontent.com/36258114/67857461-2845e680-fb17-11e9-842c-a813670e5374.png)

**Comment by pahaf19** [comment]
So I've been working on this last night. I've been able to separate the clusters almost into single beads, but there are a few beads that are still connected.

I could try to develop a watershed function or.... I think I'll just use sci-kit-image now

**Comment by nicklasfrahm** [comment]
Fixed by #24.
